name: CI/CD dos Projetos Spring Boot SnowManLabs

on:
  push:
    branches: [master]

env:
    TAG_VERSION: 120

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          
            - name: Baixando Codigos Fontes
              uses: actions/checkout@v3

            - name: Logando no Docker Hub
              uses: docker/login-action@v2.0.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: maven

            - name: Build do MS Api Livros
              working-directory: ./api-livros
              run: mvn package -Pdevelopment

            - name: Gerando Imagens dos Microsserviços
              working-directory: ./
              run: docker compose build

            - name: Enviando Imagens para o Docker Hub
              run: |
                docker tag ${{ secrets.DOCKER_USERNAME }}/ms-snow-api-livros:latest ${{ secrets.DOCKER_USERNAME }}/ms-snow-api-livros:${{ env.TAG_VERSION }}
                docker push ${{ secrets.DOCKER_USERNAME }}/ms-snow-api-livros:${{ env.TAG_VERSION }}

            - name: Realizando Deploy e Executando a Stack na VPS
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_VPS }}
                port: ${{ secrets.VPS_PORT }}
                script: |
                  docker stop $(docker ps -aq)
                  cd ../sistema/snowmanlabs
                  grep -q '^TAG_VERSION=' .env && sed -i 's/^TAG_VERSION=.*/TAG_VERSION=${{ env.TAG_VERSION }}/' .env || echo 'TAG_VERSION=${{ env.TAG_VERSION }}' >> .env
                  docker compose up -d
                  docker ps
                  